FROM node:16.17.1

RUN apt-get update -y \
    && apt-get install -y \
    vim curl wget zip htop\
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/li 

RUN npm install -g nodemon \
    && git clone https://github.com/jaywu109/node_test.git /node_test

WORKDIR /node_test

RUN  npm install 

EXPOSE 8080
ENTRYPOINT ["/bin/bash", "start.sh"]